### ISSUE TITLE
Missing instructions on how to set up dummy app

### ISSUE THREAD

**Issue by javidjamae** [stefansenk/spree_multi_tenant#1]
I'm trying to fork the project to see if I can get it to work with spree 1.2.0, but when I try to run rspec, I get this error:

/xxxx/spree_multi_tenant/spec/spec_helper.rb:4:in `require': cannot load such file -- /xxxx/spree_multi_tenant/spec/dummy/config/environment.rb (LoadError)

I noticed that this is in your .gitignore, but you don't have any directions on how to set up the dummy app in the readme file. Perhaps you could explain?

Thanks!

**Comment by stefansenk** [comment]
Hi javidjamae. Running `bundle exec rake test_app` should create your dummy app in spec/dummy. From the Readme:

```
$ cd spree_multi_tenant
$ bundle install
$ bundle exec rake test_app
$ bundle exec rspec spec
```

I've not has a chance to look at 1.2.0 yet. Good luck and let us know how you get on.

**Comment by javidjamae** [comment]
Ah, yes. I totally missed that. Thanks.

It seems to work fine with 1.2, but I haven't been able to get the test_app migration to run because of the rename from Creditcard to CreditCard. It seems to die on the migration of the test_app itself. I'm trying to work through where it gets the migrations for the dummy app right now, because I changed all of the naming in the spree_multi_tenant app already.

Once I get rspec spec to work, I'll do a pull request and perhaps you can create a 1-1-stable and 1-2-stable branch for spree_multi_tenant that lines up with the branches on spree/spree. 

Feel free to close this issue out. If you want to create a separate issue for getting the app working on 1.2, you can assign it to me.

**Comment by stefansenk** [comment]
Hi. Yes, will do. Agree it makes sense to make a 1-1-stable branch, following the spree conventions.
