### ISSUE TITLE
Can't mass-assign protected attributes: domain, code

### ISSUE THREAD

**Issue by harssh** [stefansenk/spree_multi_tenant#3]
rake spree_multi_tenant:create_tenant domain=mydomain.com code=mydomain
rake aborted!
Can't mass-assign protected attributes: domain, code

**Comment by stefansenk** [comment]
Hi harsshhfs. I've tried creating a new project for Spree 1.2 and can't repeat this issue. The Spree::Tenant model has attr_accessible set for :domain and :code, so as I understand it, it should be able to mass-assign those items. I've added a couple of tests to the latest version for the raketasks which are passing for me. Perhaps you are using an older version, before the attr_accessible was added?

**Comment by harssh** [comment]
Well I was using 1-1-stable branch and it doesn’t have attr_accessible set for :domain and :code .
I have set that on my local and was able to use the gem so no problem now ....
You can check here
https://github.com/stefansenk/spree_multi_tenant/blob/1-1-stable/app/models/spree/tenant.rb 
:)
